"""Shared thresholds and config used by processing services."""

EARTH_RADIUS_M = 6_371_000.0
GRAVITY_MS2 = 9.80665
LOW_VOLTAGE_THRESHOLD = 3.5
VIBE_WARNING_THRESHOLD = 30
VIBE_CRITICAL_THRESHOLD = 60
MOTOR_MAX_PWM = 2000
MOTOR_MIN_PWM = 1000
MOTOR_SATURATION_MARGIN = 50

MIN_SATS = 6
MAX_HDOP = 2.5
ALT_MEDIAN_K = 7
MAX_PLAUSIBLE_H_SPEED = 200.0
MAX_PLAUSIBLE_ALT_GAIN_WARN_M = 1200.0
MAX_PLAUSIBLE_ALT_DELTA_PER_SAMPLE_M = 10.0
MAX_PLAUSIBLE_ALT_MSL_M = 9000.0

GYRO_EXTREME_WARN_DEG_S = 500.0
MAP_TRAJECTORY_PADDING_FRAC = 0.2

# EKF initialization
EKF_INIT_IMU_SAMPLES = 50
EKF_INIT_LEVEL_G_TOL = 1.5
EKF_INIT_LEVEL_TIMEOUT_S = 2.0
EKF_ADAPTIVE_MIN_SAMPLES = 10
EKF_ADAPTIVE_WINDOW = 5
EKF_ADAPTIVE_DELTA_MS2 = 0.5
EKF_ADAPTIVE_IN_FLIGHT_MAG_MS2 = 10.3

MESSAGE_TYPES = [
    "ATT",
    "GPS",
    "BAT",
    "VIBE",
    "RCOU",
    "RCIN",
    "IMU",
    "MODE",
    "ERR",
    "MSG",
    "EV",
    "BARO",
]
